### ISSUE TITLE
`getAllParametersMatching()` broken?

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/OSPSuite-R#1364]
Trying to get all parameters located somewhere in "Applications":

```
library(ospsuite)

simFilePath <- system.file("extdata", "Aciclovir.pkml", 
                           package = "ospsuite")
simExercise <-loadSimulation(simFilePath)
getAllParametersMatching("**|Applications|**", simExercise)
```

Version 11.2:

```
[[1]]
Parameter: 
   Path: Applications|IV 250mg 10min|Application_1|Application rate 
   Value: 0.00 [µmol/min] 
   isConstant: TRUE 
   isStateVariable: FALSE 

[[2]]
Parameter: 
   Path: Applications|IV 250mg 10min|Application_1|Volume 
   Value: 1.00 [l] 
   isConstant: TRUE 
   isStateVariable: FALSE 

[[3]]
Parameter: 
   Path: Applications|IV 250mg 10min|Application_1|ProtocolSchemaItem|Start time 
   Value: 0.00 [min] 
   isConstant: TRUE 
   isStateVariable: FALSE 

[[4]]
Parameter: 
   Path: Applications|IV 250mg 10min|Application_1|ProtocolSchemaItem|Dose 
   Value: 0.00 [kg] 
   isConstant: TRUE 
   isStateVariable: FALSE 

[[5]]
Parameter: 
   Path: Applications|IV 250mg 10min|Application_1|ProtocolSchemaItem|DosePerBodySurfaceArea 
   Value: 0.00 [kg/dm²] 
   isConstant: TRUE 
   isStateVariable: FALSE 

[[6]]
Parameter: 
   Path: Applications|IV 250mg 10min|Application_1|ProtocolSchemaItem|DosePerBodyWeight 
   Value: 0.00 [kg/kg] 
   isConstant: TRUE 
   isStateVariable: FALSE 

[[7]]
Parameter: 
   Path: Applications|IV 250mg 10min|Application_1|ProtocolSchemaItem|DrugMass 
   Value: 1110.08 [µmol] 
   isFormula: TRUE 
   formula: Dose / MW 
   Value overrides formula: FALSE 
   isStateVariable: FALSE 

[[8]]
Parameter: 
   Path: Applications|IV 250mg 10min|Application_1|ProtocolSchemaItem|Infusion time 
   Value: 10.00 [min] 
   isConstant: TRUE 
   isStateVariable: FALSE 

[[9]]
Parameter: 
   Path: Applications|IV 250mg 10min|Application_1|Aciclovir|Concentration 
   Value: 1110.08 [µmol/l] 
   isFormula: TRUE 
   formula: V>0 ? M/V : 0 
   Value overrides formula: FALSE 
   isStateVariable: FALSE 
```

Version 12:

`NULL`
