### ISSUE TITLE
calculatePKAnalyses - why not all PK-parameters are calculated?

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/OSPSuite-R#792]
For the Aciclovir-example (also used in the vignette https://www.open-systems-pharmacology.org/OSPSuite-R/articles/pk-analysis.html), these PK-Parameters are calculated:

```
SimulationPKAnalyses: 
For outputs: 
   Organism|PeripheralVenousBlood|Aciclovir|Plasma (Peripheral Venous Blood): 
   Organism|Age: 
   Organism|ArterialBlood|Plasma|Aciclovir: 
For pK-Parameters: 
   C_max: 
   C_max_norm: 
   t_max: 
   C_tEnd: 
   AUC_tEnd: 
   AUC_tEnd_norm: 
   AUC_inf: 
   AUC_inf_norm: 
   MRT: 
   Thalf: 
   FractionAucLastToInf: 
   CL: 
   Vss: 
   Vd: 
```

What about the other parameters listed in `StandardPKParameter`? E.g. C_min?
